### PR TITLE
Made parser pluggable, related to #7

### PR DESCRIPTION
**Pull request by puzrin**
Now lexer instances can be configured, as discused in #7. That allows to add new rules, remove/replace existing ones and so on. This commit preserve compatibility with existing API.

Futher improvements require api change.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
done, looks great! fwiw I'm completely open to API changes. IMO there is no advantage in trying to remain compatible with marked.js.

**Comment by jonschlinkert** [comment]
I added you as a collaborator. Also, please add your name or whoever you want to `maintainers` in package.json.

**Comment by howardroark** [comment]
I am happy to see some great cooperation going on here!  I have been watching the marked project for a while and it does not seem to evolve well.  I can see that the original creator does not "watch" the project, which could contribute to this problem.  I'd say that right now it suffers from a general lack of leadership.

**Comment by jonschlinkert** [comment]
:+1: thanks @howardroark! great words of encouragement. The nerd in me is super excited about this too, I love doing this stuff lol

**Comment by puzrin** [comment]
BTW, @Kirill89 broken `.setOption()` call for singleton, will push fix with additional tests today or tomorrow. Now just pushed some more cleanup & benchmarks to control process better.

**Pull request merged**
